
apiVersion: v1
kind: Namespace
metadata:
  name: node-red
  labels:
    app: nodered
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered-deployment
  namespace: node-red
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: nodered-service-cluster-ip
  namespace: node-red
spec:
  type: LoadBalancer
  selector:
    app: nodered
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1880