apiVersion: v1
kind: Service
metadata:
  name: nodered-service-cluster-ip
  namespace: node-red
spec:
  type: LoadBalancer
  selector:
    app: nodered
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1880